### ISSUE TITLE
Add additional twitter announcements

### ISSUE THREAD

**Issue by liambaloh** [OneHourGameJam/DiscordBot#3]
Ideally I'd like the following:
24h before jam: 1 hour game jam tomorrow at this time! That's 7AM ACT, Midday PST, 3PM EST, 8PM UTC and 9PM CET. https://onehourgamejam.com
16h before jam: 1 hour game jam starts in 16h! At 7AM ACT, Midday PST, 3PM EST, 8PM UTC and 9PM CET. https://onehourgamejam.com
8h before jam: 1 hour game jam starts in 8h! At 7AM ACT, Midday PST, 3PM EST, 8PM UTC and 9PM CET. https://onehourgamejam.com
4h before jam: 1 hour game jam starts in 4h! Participate at https://onehourgamejam.com
2h before jam: 1 hour game jam starts in 2h! Participate at https://onehourgamejam.com
1h before jam: 1 hour game jam starts in 1h! Join us on Discord at https://discord.gg/J86uTu9
20 minutes before jam: 1 hour game jam starts in 1 minutes! Join us on Discord at https://discord.gg/J86uTu9
A few seconds after jam starts (to ensure API has theme): 1 hour game jam #123 started. The theme is: "Space". Participate at https://onehourgamejam.com

Open to alternative suggestions, obviously. The above are proposals. The idea is to have the 24h, 16h and 8h notification cover all time zones, and then the 4h, 2h, 1h and 20min notifications serving as reminders for people who browse twitter.

Oh and please double-check the times I wrote...

**Comment by LongarMD** [comment]
Should this also account for daylight savings time? I forgot, is that still a thing?
Also, for the theme announcement we could add a picture to the tweet that relates to the theme. This could be done with getting the first image from a google image search of the theme. What do you think?

**Comment by liambaloh** [comment]
Ideally it would adjust for daylight savings time, though that can be done manually too. For the image thing, I would advise against it, for the reasons I outlined in https://github.com/OneHourGameJam/OneHourGameJam/issues/90. To get that to work, I'd recommend admins choose a suitable image when the jam is scheduled. While a helper function could exist that lists out some images for the admin to choose from, I would not have it be fully automatic.
