### ISSUE TITLE
Fix double space in !time command response

### ISSUE THREAD

**Issue by liambaloh** [OneHourGameJam/DiscordBot#4]
Appears when there is 1 hour and 0 minutes to go

![discord_2019-02-09_19-00-21](https://user-images.githubusercontent.com/1364475/52525145-360fbf00-2c9d-11e9-98b9-56edeae5f030.png)

**Comment by LongarMD** [comment]
The optimal solution would probably be without using `string.replace()` ... probably

**Comment by liambaloh** [comment]
I think we need to escalate this issue! It has shown up again during last week's game jam! 😮

**Comment by liambaloh** [comment]
THANK YOU 💚💚💚💚💚💚

**Comment by LongarMD** [comment]
:green_heart::green_heart::green_heart:
